[package]
name = "derive_deref"
version = "1.0.0"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]
license = "MIT OR Apache-2.0"
description = "Adds `#[derive(Deref)]` and `#[derive(DerefMut)]`"
readme = "README.md"
keywords = ["derive", "deref"]
repository = "https://github.com/sgrif/derive_deref"

[dependencies]
syn = { version = "0.11.11", features = ["aster"] }
quote = "0.3.12"

[lib]
proc-macro = true
